# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - payload-entra-id

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    env:
      COSMOS_RESOURCE_GROUP: ${{ secrets.COSMOS_RESOURCE_GROUP }}
      COSMOS_ACCOUNT_NAME: ${{ secrets.COSMOS_ACCOUNT_NAME }}
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
 
      - name: create .env
        run: |
          cat << EOF > .env
          DATABASE_URI=${{ secrets.DATABASE_URI }}
          PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
          NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          CRON_SECRET=${{ secrets.CRON_SECRET }}
          PREVIEW_SECRET=${{ secrets.PREVIEW_SECRET }}
          AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }}
          AUTH_URL=${{ secrets.AUTH_URL }}
          AUTH_SECRET=${{ secrets.AUTH_SECRET }}
          AUTH_MICROSOFT_ENTRA_ID_TENANT_ID=${{ secrets.AUTH_MICROSOFT_ENTRA_ID_TENANT_ID }}
          AUTH_MICROSOFT_ENTRA_ID_CLIENT_ID=${{ secrets.AUTH_MICROSOFT_ENTRA_ID_CLIENT_ID }}
          AUTH_MICROSOFT_ENTRA_ID_SECRET=${{ secrets.AUTH_MICROSOFT_ENTRA_ID_SECRET }}
          EOF
          chmod 600 .env
          echo "Environment file created for $(echo $NODE_ENV) environment"
        env:
          NODE_ENV: production

      - name: Debug network connectivity
        run: |
          # 接続先ホストへのネットワーク接続をテスト
          ping -c 4 payload-entra-id-server.mongo.cosmos.azure.com || echo "Ping failed but that's expected for CosmosDB"
          # Telnetで10255ポートへの接続をテスト
          nc -zv payload-entra-id-server.mongo.cosmos.azure.com 10255
          # 外部IPアドレスを確認（これをAzureのファイアウォール許可リストに追加できます）
          curl -s https://api.ipify.org
              
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7EDF5836BD294C0182F3A46120AD253C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E82D9FECEB404EDD85AB41851317036D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F54FCA572DC74BE8A4E4CBAD2DDD50B7 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'payload-entra-id'
          slot-name: 'Production'
          package: dist  # ビルド済みの成果物のみ
          startup-command: 'npm start'          
